### ISSUE TITLE
Plugin Settings Not Storing

### ISSUE THREAD

**Issue by Dulanic** [binhex/arch-delugevpn#66] opened 2018-06-18 00:55 UTC
So I know this has been mentioned before, but I'd like to make an ticket to track research. I am going to dig in a bit more as I have time also to see if I can figure anything out also.

Issue: Plugins lose settings upon container resets.

**Comment by Dulanic** [comment] 2018-06-18 01:02
As a follow up, is there a easy way for me to edit the plugin settings upon container start? I wasnt sure what runs on startup. Ill dig in, but if you can specify off hand, might help.

**Comment by johanndt** [comment] 2018-06-18 10:32
I don't think it's saving properly. I just tried to turn on the label plugin and while it seems to turn on in the client, I see the following in the logs:
```
[INFO    ] 20:14:30 core:97 *** Start Label plugin ***
[WARNING ] 20:14:30 config:369 Unable to open config file /config/label.conf: [Errno 2] No such file or directory: '/config/label.conf'
[INFO    ] 20:14:30 pluginmanagerbase:158 Plugin Label enabled..
```

Looking in /config/core.conf I can see there's a item for `"enabled_plugins": [],`, and also `"plugins_location": "/config/plugins",`. But these don't appear to get updated when enabling a plugin.

I guess if we fix this, then it should start working.

I found this thread: https://forum.deluge-torrent.org/viewtopic.php?t=45287

Reading the last message, I tried the same. In the web GUI go to connection manager, stop the daemon. Then restart it. Checking core.conf now shows the Label plugin listed in `enabled_plugins`.

**Comment by Dulanic** [comment] 2018-06-18 12:29
So the enabled plugins seem to work, but sometimes seem to add every time, see https://github.com/binhex/arch-delugevpn/issues/61 . However, the plugin settings are not working. Enabled plugins stays persistent between resets it seems. However, the .conf files for the plugins revert to their default each restart. Label seems to be an exception, so I don't know the cause.

Extractor.conf before restart:
```
{
  "file": 1, 
  "format": 1
}{
  "use_name_folder": true, 
  "extract_path": "/downloads/extracted"
}
```
After restart:
```
{
  "file": 1, 
  "format": 1
}{
  "use_name_folder": false, 
  "extract_path": ""
}
```

I have validated this works fine outside of docker and manually installed.

**Comment by johanndt** [comment] 2018-07-06 10:33
So I had some time to try this again and I enabled the Execute plugin. Then I added 1 command to it's config, and restarted the container with `docker restart delugevpn`. When I could log in again the config still had the same command I had set in there before:

```
[root@182bf65f156d config]# cat execute.conf
{
  "file": 1, 
  "format": 1
}{
  "commands": [
    [
      "ab954f596335631ee333d0629c5233c55b245538", 
      "complete", 
      "/bin/true"
    ]
  ]
}
```
So at least it seems like it's not all plugins forgetting their settings. I'll test the Label plugin next like you did.

**Comment by cpero** [comment] 2018-08-15 22:16
I too am having the same issue, however I discovered a neat workaround. Running this container from default, I was unable to store plugin settings and was experiencing the same issues also highlighted in #61. However, after restoring a backup of my `deluge` folder containing all of my previous settings and configs from a different machine, everything worked perfectly (assuming you don't want to change any plugins). After this, I experienced some weird behavior where sometimes plugin settings would save after clicking apply, sometimes they wouldn't, but after getting them "locked in" (no clue what made it work here besides try over and over) they now launch correctly and with the correct configurations and no spooky behavior.

**Comment by ZataH** [comment] 2018-12-09 11:31
I have the same issue. My SimpleExtract plugin keep resetting it self, and password for deluge does not keep saved.

**Comment by sundarnet** [comment] 2019-02-27 05:45
+1 for labels plugin not remembering its been enabled

**Comment by binhex** [comment] 2019-02-28 17:57
from the poking about ive done over time this looks to be a deluge bug, permissions are set correctly, you can add plugins in but some do not 'stick' and others you end up with duplicate entries showing, dunno why, but i got my fingers crossed that this is all fixed in the new shiny deluge 2.x which should be out soon(ish).

**Comment by Petahh** [comment] 2019-03-05 08:17
I had similar problem as you guys, bit of manual actions resolved it however. I will sum it up for anyone who is looking for quick solution to this.
1. Make sure that your plugin conf files are present and accessible. example: `config/label.conf `
2. Edit `config/core.conf` and add below lines to enable plugins, example:
```
  "enabled_plugins": [
    "Label",
    "Scheduler",
    "Notifications"
  ],
```

**Comment by binhex** [comment] 2019-06-18 16:08
ugghh! sadly this is STILL not fixed in deluge 2.0.3, so looks like its still a manual hack to get plugins to stay enabled, not good :-(

**Comment by binhex** [comment] 2019-07-03 14:03
A bit more investigation on this, so it looks like deluge weirdly only saves settings made to plugins section (maybe other settings to?) on shutdown!, problem is of course that because deluge is running in a container, when deluge shuts down so does the entire os (container) and thus there is no chance to write the settings out, resulting in things like enablement of plugins not 'sticking'. in my mind this is a deluge bug.

**Comment by binhex** [comment] 2019-08-20 09:55
closing the issue off but leaving pinned, also of note i have now created a FAQ for this issue, see here Q4.:- https://github.com/binhex/documentation/blob/master/docker/faq/delugevpn.md

**Closed by binhex** 2019-08-20 09:55 UTC

**Comment by MrScottah** [comment] 2020-03-30 05:30
Still having this issue.

**Comment by marc0janssen** [comment] 2020-04-09 12:06
I'm having this issues too

**Comment by binhex** [comment] 2020-04-09 13:20
if the plugin is not made for deluge v2 then you will be out of luck until the plugin developer updates the plugin to work with python 3.x

**Comment by marc0janssen** [comment] 2020-04-09 20:03
Hi @binhex , Thanks for replying.. but I fixed it with the hint from @Petahh

**Comment by itsananderson** [comment] 2021-02-04 07:40
I know this is a very old (and closed) ticket, but I was curious about the root cause of this issue, so I did some digging this evening.

Theoretically Deluge should write its config when it receives a shutdown signal (`SIGTERM`). In fact, I tested this behavior by running `pgrep deluged | xargs kill -TERM` on the docker machine. When I did that, the Deluge daemon was shut down, but before it did, it wrote out its config. Eventually `watchdog.sh` detects that the Deluge daemon isn't running and restarts it.

Normally when a Docker container shuts down, the entrypoint *should* receive a SIGTERM. However, since Deluge daemon is started as a background process it doesn't automatically receive this SIGTERM signal. It looks like the Docker image is supposed to [kill the `deluged` and `deluge-web` processes at shutdown](https://github.com/binhex/arch-delugevpn/blob/master/build/delugevpn.conf#L19) but `shutdown.sh` doesn't actually seem to exist on the latest image. Looking at the Git history of https://github.com/binhex/scripts, I think the issue is that `shutdown.sh` was only added on [December 27th](https://github.com/binhex/scripts/commit/b250882b22076c3ab2d94740f7079a137985a08e#diff-e2d079ee968720b8603e2e913dfdbe03ac15c0f3e8a4fc5f60196e3bc9a14e3d) but the latest release of `arch-delugevpn` was on [December 1st](https://hub.docker.com/layers/binhex/arch-delugevpn/latest/images/sha256-e05c8698c439da9eb5e8438f2ff074078771cf5bce1834ce68d5d2a9c6595e74?context=explore), so it's missing the `shutdown.sh` script. I *think* that means simply publishing a new version of this Docker image (and thus pulling in the latest binhex/scripts) would be enough to actually fix this bug.

**Comment by binhex** [comment] 2021-02-04 16:11
> I think the issue is that `shutdown.sh` was only added on [December 27th](https://github.com/binhex/scripts/commit/b250882b22076c3ab2d94740f7079a137985a08e#diff-e2d079ee968720b8603e2e913dfdbe03ac15c0f3e8a4fc5f60196e3bc9a14e3d) but the latest release of `arch-delugevpn` was on [December 1st](https://hub.docker.com/layers/binhex/arch-delugevpn/latest/images/sha256-e05c8698c439da9eb5e8438f2ff074078771cf5bce1834ce68d5d2a9c6595e74?context=explore), so it's missing the `shutdown.sh` script. I _think_ that means simply publishing a new version of this Docker image (and thus pulling in the latest binhex/scripts) would be enough to actually fix this bug.

correct!, shutdown.sh is a relatively new introduction to all of my images, but i have been hesitant about pressing the button at the moment, especially as the issue is reasonably minor for deluge. i will be rebuilding the image at some point im sure, and at that point shutdown.sh wil be included and should finally fix this issue.

**Comment by itsananderson** [comment] 2021-02-04 17:58
👍 No need to rush out a new release just for this. I mostly commented for awareness, since it might not have been obvious that the issue will be resolved with the next image update. Plus I spent a couple hours poking at the container to figure out what was going on, so I felt like I should record my findings 😂
