### ISSUE TITLE
"/bin/bash: /root/init.sh: No such file or directory" error. Running "Latest- 2.0.3-1-05" on Synology 6.2.2

### ISSUE THREAD

**Issue by BladesKnight** [binhex/arch-delugevpn#124] opened 2019-08-15 05:29 UTC
Hi,

Trying to set up this docker but its throwing up this error on starting up.

Path is set to: /usr/local/sbin:/usr/local/bin:/usr/sbin:usr/bin/:/sbin:/bin

Any ideas pls?

Thank you!

**Comment by binhex** [comment] 2019-08-15 16:48
im not sure what image you are running their but it cant be the latest, please do:-
```
docker pull binhex/arch-delugevpn:latest
```
then re-create the container.

**Comment by NobQuaffer** [comment] 2019-08-15 19:12
Hi Binhex,
I’m experiencing the same issue. Ourobouros updated Delugevpn last night to the latest build. I’ve recreated it and told it to pull the image again but no joy. 
The Deluge UI is unavailable and the VPN/proxy is unavailable.

I’ll roll back to the previous build and see if it works again.

**Comment by NobQuaffer** [comment] 2019-08-15 20:02
Confirmed, rolling back to older build resolved the issue

**Comment by binhex** [comment] 2019-08-16 12:05
@NobQuaffer are you 100% sure the issue is identical to the OP? are you seeing that EXACT same message regards init.sh?, the lack of access to the web ui does not mean you have the same issue, there are dozens of reasons for this, please confirm.

**Comment by binhex** [comment] 2019-08-16 12:29
@BladesKnight just to be clear, i have pulled the latest image and can confirm no issues with startup, please can you do the following if its still an issue:-
https://github.com/binhex/documentation/blob/master/docker/faq/help.md

also post your full docker run command here too.

**Comment by NobQuaffer** [comment] 2019-08-16 12:31
Hi @binhex,
Yep, I was seeing the exact same error in the logs, repeated hundreds of times, line after line. 
Unlike OP, I’m running on Ubuntu and it was working fine prior to the update. 

I’ve reverted and it’s working fine now. I’ll update to the latest again and see if the issue returns.

**Comment by NobQuaffer** [comment] 2019-08-16 12:34
@binhex, yup, upgraded to last and the issue returned:


/bin/bash: /root/init.sh: No such file or directory

Rolled back and working fine again. Weird stuff!

**Comment by BladesKnight** [comment] 2019-08-16 12:36
Likewise, docker was working perfectly fine on 2.0.3-1-03 and all other earlier releases. It only failed to start with the "Latest" which has a build date of 3 days ago.

**Comment by NobQuaffer** [comment] 2019-08-16 12:40
No idea if it’s relevant but I installed it using dockSTARTer out of laziness.

**Comment by NobQuaffer** [comment] 2019-08-16 12:46
@binhex, I’ll try to perform the steps you detailed in help.md at some point but I’m currently redecorating my house and my server is difficult to access. I’ve only really got access to Portainer using my phone at the moment :/ I’ll try to be more helpful as soon as I can ^_^

**Comment by BladesKnight** [comment] 2019-08-16 13:12
Rolled it back to 2.0.3-1-03 and it starts up without errors. Same errors encountered on 2.0.3-1-04.

**Comment by binhex** [comment] 2019-08-16 13:19
ok can you guys do the following via command line, so no third party apps:-

1. run this command to ensure we have the latest image on disk:-
`docker pull binhex/arch-delugevpn:latest`
please post the output of this command here.

2. delete your existing container, and then re-create by using the 'docker run...' command, again please post your docker run command you are using here.

just as a confidence check, here is the line of code in the current committed script, as you can see on line 58 its NOT referencing /root/init.sh:-
https://github.com/binhex/arch-delugevpn/blob/master/Dockerfile

the latest image was built with this commit (last build was 3 days ago) and thus will include the above commit.

this is the commit you guys are seeing, note it was 28 days ago:-
https://github.com/binhex/arch-delugevpn/commit/4759614b8d9ff896148f08806006dd616c469615#diff-3254677a7917c6c01f55212f86c57fbf

so you guys MUST be running an old image.

**Comment by haxx0r07** [comment] 2019-08-16 14:22
I'm also seeing the same issue with my setup (running Docker on top of OpenMediaVault)


Output of the "docker pull binhex/arch-delugevpn:latest"
`docker pull binhex/arch-delugevpn:latest
latest: Pulling from binhex/arch-delugevpn
Digest: sha256:71777561b0488d409ffe07d69d3344dfd979ef08cb0f8ea2d22cc6e4fab23760
Status: Image is up to date for binhex/arch-delugevpn:latest
docker.io/binhex/arch-delugevpn:latest
`


Looking at the details of the pulled docker image I see this 
`"Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/bash\" \"/usr/local/bin/init.sh\"]"
            ],
`


However, looking at the details of my deployed container I see this.
`"Cmd": [
                "/bin/bash",
                "/root/init.sh"
            ],
`

**Comment by binhex** [comment] 2019-08-16 14:34
```
However, looking at the details of my deployed container I see this.
"Cmd": [ "/bin/bash", "/root/init.sh" ],
```

are you deleting the existing container? before re-deploying the container?

**Comment by haxx0r07** [comment] 2019-08-16 14:40
I use ouroboros to update my containers nightly. Looking at the overview for ouroboros it states:

> Ouroboros will monitor (all or specified) running docker containers and update them to the (latest or tagged) available image in the remote registry. The updated container uses the same tag and parameters that were used when the container was first created such as volume/bind mounts, docker network connections, environment variables, restart policies, entrypoints, commands, etc.

Looking at my containers themselves it appears that ouroboros deletes the old container and creates a new one.

**Comment by binhex** [comment] 2019-08-16 14:50
```
I use ouroboros to update my containers nightly.
```
interesting, so does @NobQuaffer 
```
I’m experiencing the same issue. Ourobouros updated Delugevpn last night
```

so is the common factor here that people with the issue are all using Ourobouros?. FWIW i tried doing a pull and run on my mac and no issues whatsoever, container was created and runs without issue.

**Comment by haxx0r07** [comment] 2019-08-16 14:58
It seems that way, but how do we explain that @BladesKnight is experiencing?  Hey @BladesKnight are you trying to deploy this as a brand new container, or are you using ouroboros to update your containers as well?

**Comment by BladesKnight** [comment] 2019-08-16 15:09
I'm not using that. I'm just using the docker app on the Synology NAS. I tried upgrading as well as a brand new container. Both threw the same error for the 2 latest images. Works fine without errors when using 2.0.3-1-03.

**Comment by binhex** [comment] 2019-08-16 15:10
> I'm not using that. I'm just using the docker app on the Synology NAS.

please try doing a docker run from the command line, who knows what the synology 'docker app' is actually doing.

**Comment by BladesKnight** [comment] 2019-08-16 15:14
What changed tho between version 03 and 04/05? Seems to be causing issues with various apps and environments?

**Comment by binhex** [comment] 2019-08-16 15:17
> What changed tho between version 03 and 04/05? Seems to be causing issues with various apps and environments?

a fair bit tbh, mainly enhancing the ability to detect and grab a new port when marked as closed. the thing is i cannot reproduce the issue you guys are seeing, and until i can there is nothing for me to fix, keep in mind this image has had so far 10 million+ downloads, if the image was baulked there would be a LOT of people on here complaining.

i could just kick off another build with no code changes i guess, but i would rather not unless i have to.

**Comment by haxx0r07** [comment] 2019-08-16 15:29
I'm going to manually try rebuilding my deployed container here afterwhile and I'll report back. 

Just FYI I'm also having this issue with the binhex/arch-nzbhydra2 container as well, but I'm guessing you made similar changes to it and my issue is just due to the way ouroboros re-deploys the containers.

**Comment by binhex** [comment] 2019-08-16 15:34
> Just FYI I'm also having this issue with the binhex/arch-nzbhydra2 container as well, but I'm guessing you made similar changes to it and my issue is just due to the way ouroboros re-deploys the containers.

there was the change in the init script location for all the docker images i produced, however the change wont show up unless the image is rebuilt (triggered by an update in the application version) - nzbhydra2 is one of those images that has been rebuilt.

**Comment by haxx0r07** [comment] 2019-08-16 15:54
Cool, just one more thing that points to it not being an issue in your containers.  I'll update this issue post once I re-deploy mine.

**Comment by haxx0r07** [comment] 2019-08-19 14:48
I was able to manually re-deploy my deluge container and it came up without any issues, once I added in some new environment variables (LAN Network). Although now my radarr and sonarr containers can't connect to it. I'm thinking this is due to something getting messed up with the API plugin.

**Comment by binhex** [comment] 2019-08-20 09:53
> I was able to manually re-deploy my deluge container and it came up without any issues,

awesome!, thanks for confirming that the issue is related to 'Ourobouros' please post a issue on their github repo.

> once I added in some new environment variables (LAN Network).

im not sure how often you update, but lan_network has been a env var for a LONG time (a number of years), maybe you dont update very often? :-)

> Although now my radarr and sonarr containers can't connect to it. I'm thinking this is due to something getting messed up with the API plugin.

please post this as a separate issue, i want to close this off.

**Comment by haxx0r07** [comment] 2019-08-20 17:27
@binhex Yep, this issue was caused by something in ouroboros on my side at least. I deployed the initial containers maybe a year ago. Maybe the lan network wasn't required at that time, or most likely I just missed copying that variable to my new build command. 

The radarr/sonarr issue was to do with deluge 2.0 auth method. The sonarr/radarr containers had been deprecated and were no longer being maintained. I switched them over to a new maintainer and all is working now. 

I'd say this is good to close. I'll open an issue with ouroboros and link back if required.

**Comment by binhex** [comment] 2019-08-20 17:34
Ok great thanks for letting me know, btw I also author sonarr and radarr images amongst others 😁

**Closed** 2019-08-20 17:34 UTC

**Comment by Melantrix** [comment] 2020-04-01 18:21
I know this has been closed for a while now, but i just wanted to add something for users running docker on synology on how to fix this issue so please feel free to close it again right away:

Normally to update a docker image on synology you remove the image in the downloaded image repo. then you clear the image and start it up again. However, synology saves the execution command which is changed in the newer version. 

If you try to export the settings, and import that file again, you will also export and import the wrong execution command. 

However, an easy way to fix this is to export the settings of the docker, open it in a file editor and change the line:
`"cmd" : "/bin/bash /root/init.sh"` 

into:
`"cmd" : "/bin/bash /usr/local/bin/init.sh"`

you can then import the file and run the docker without issues.

**Comment by Coder84619** [comment] 2020-07-02 23:31
> I know this has been closed for a while now, but i just wanted to add something for users running docker on synology on how to fix this issue so please feel free to close it again right away:
> 
> Normally to update a docker image on synology you remove the image in the downloaded image repo. then you clear the image and start it up again. However, synology saves the execution command which is changed in the newer version.
> 
> If you try to export the settings, and import that file again, you will also export and import the wrong execution command.
> 
> However, an easy way to fix this is to export the settings of the docker, open it in a file editor and change the line:
> `"cmd" : "/bin/bash /root/init.sh"`
> 
> into:
> `"cmd" : "/bin/bash /usr/local/bin/init.sh"`
> 
> you can then import the file and run the docker without issues.

THANK you so much! Synology user here and was baffled with the same issue. Your post fixed it!
