### ISSUE TITLE
Deluge not compatible with newer version of libtorrent

### ISSUE THREAD

**Issue by middleagedman** [binhex/arch-delugevpn#20] opened 2017-02-17 03:40 UTC
Just noticed I was getting this in my error logs

017-02-16 21:11:06,628 DEBG 'deluge-script' stderr output:
/usr/lib/python2.7/site-packages/deluge/_libtorrent.py:59: RuntimeWarning: to-Python converter for boost::shared_ptr<libtorrent::alert> already registered; second conversion method ignored.
  import libtorrent as lt

http://forum.deluge-torrent.org/viewtopic.php?f=7&t=53939#p223925

Not sure what the fix is, as this is an older post and supposedly it was fixed

**Comment by 00Asgaroth00** [comment] 2017-03-02 22:17
I can confirm, I was just reading a thread in the deluge forums relating to the ltconfig plugin. It looks like deluge v 1.3.13 only does not support libtorrent 1.1.x. Apparently a lter edition of 1.3.x is going to support it

Is it possible to downgrade to libtorrent 1.0.x in this image? We cannot use the ltconfig plugin in deluged if we run with libtorrent v1.1.x.

Additionally I'm having issues with socks proxy setting that deluge is currently not using even when set, so i need ltconfig so i can set it in libtorrent directly.

Any assistance would be appreciated.

For reference, the deluge forum thread I was reading is [here](http://forum.deluge-torrent.org/viewtopic.php?f=9&t=42887&start=80#p224769)

**Comment by 00Asgaroth00** [comment] 2017-03-04 09:56
Just an update, it appears that deluge 1.3.13 will only run on 1.0.x (currently 1.0.11), that version does not support 1.1.x.

Apparently deluge v1.1.14 will support the 1.1.x range of libtorrent, but I have no idea when 1.1.14 will be released.

Any chance of a downgrade of libtorrent in this image?

**Comment by binhex** [comment] 2017-03-08 10:34
sure, leave it with me.

**Comment by 00Asgaroth00** [comment] 2017-03-08 10:37
Thanks, much appreciated :)

**Comment by 00Asgaroth00** [comment] 2017-03-08 11:10
Actually, I have just noticed that deluge was also updated to version 1.3.14 yesterday, it appears to officially support 1.0.11.

Would it be possible to include the updated deluge v1.3.14 as well, or should I open another ticket?

See thread [here](http://forum.deluge-torrent.org/viewtopic.php?f=7&t=54430) and official release [here](http://dev.deluge-torrent.org/wiki/ReleaseNotes/1.3.14)

**Comment by 00Asgaroth00** [comment] 2017-03-08 11:14
it appears that v1.3.14 also fixes some https via proxy related issues too, specifically the following issues

[Ticket 2149](http://dev.deluge-torrent.org/ticket/2149)

**Comment by binhex** [comment] 2017-03-08 11:20
yes i spotted deluge 1.3.14 release and that got built last night, i also had in mind this issue you raised and hoped it was fixed in .14 but it looks like there are still some problems as i was still seeing the module import error when deluge starts up.

i will take another look tonight in depth and see whats going on.

**Comment by binhex** [comment] 2017-03-08 13:24
yep looking at the changelog there is no ref to support libtorrent 1.1.x, looks like this will be done when deluge 2.x is released, so im going to proceed with the fix by downgrading the libtorrent version

http://dev.deluge-torrent.org/wiki/ChangeLog

**Comment by binhex** [comment] 2017-03-08 17:33
ok this is now done and the log now looks clean on boot so im fairly confident its fixed, please pull down the image and give it a whirl. im going to close this for now, if its still broken for you then i will reopen it.

**Closed by binhex** 2017-03-08 17:33 UTC
