### ISSUE TITLE
"docker-compose up deluge" works, "docker-compose up" does not

### ISSUE THREAD

**Issue by wsw70** [binhex/arch-delugevpn#110] opened 2019-05-06 11:25 UTC
I created a `docker-compose` service for `arch-delugevpn`:

```
  deluge:
    image: binhex/arch-delugevpn:latest
    container_name: deluge
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=999
      - PGID=999
      - VPN_ENABLED=yes
      - VPN_USER=<login>
      - VPN_PASS=<password>
      - VPN_PROV=pia
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.10.0/24
      - NAME_SERVERS=1.1.1.1,8.8.4.4
      - UMASK=000
      - DEBUG=false
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=debug
    volumes:
      - $PWD/deluge/config:/config
      - /mnt/2TB1/deluge:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      caddy.address: http://deluge.my.domain
      caddy.targetport: "8112"
```

When starting it individually via `docker-compose up deluge` I get a correct startup and a fully working container:

```
root@srv /e/docker# docker-compose up deluge
Recreating deluge ... done
Attaching to deluge
deluge           | Created by...
deluge           | ___.   .__       .__
deluge           | \_ |__ |__| ____ |  |__   ____ ___  ___
deluge           |  | __ \|  |/    \|  |  \_/ __ \\  \/  /
deluge           |  | \_\ \  |   |  \   Y  \  ___/ >    <
deluge           |  |___  /__|___|  /___|  /\___  >__/\_ \
deluge           |      \/        \/     \/     \/      \/
deluge           |    https://hub.docker.com/u/binhex/
deluge           |
deluge           | 2019-05-06 13:10:25.153235 [info] System information Linux ee56835d263f 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 GNU/Linux
deluge           | 2019-05-06 13:10:25.179594 [info] PUID defined as '999'
deluge           | 2019-05-06 13:10:25.256661 [info] PGID defined as '999'
deluge           | 2019-05-06 13:10:25.328264 [info] UMASK defined as '000'
deluge           | 2019-05-06 13:10:25.361891 [info] Permissions already set for volume mappings
deluge           | 2019-05-06 13:10:25.391162 [info] DELUGE_DAEMON_LOG_LEVEL defined as 'info'
deluge           | 2019-05-06 13:10:25.416152 [info] DELUGE_WEB_LOG_LEVEL defined as 'debug'
deluge           | 2019-05-06 13:10:25.441148 [info] VPN_ENABLED defined as 'yes'
deluge           | 2019-05-06 13:10:25.471236 [info] OpenVPN config file (ovpn extension) is located at /config/openvpn/Switzerland.ovpn
(...)
```

When starting it as part of the global `docker-compose up`, it fails to start:

```
# docker-compose logs deluge
Created by...
___.   .__       .__
\_ |__ |__| ____ |  |__   ____ ___  ___
 | __ \|  |/    \|  |  \_/ __ \\  \/  /
 | \_\ \  |   |  \   Y  \  ___/ >    <
 |___  /__|___|  /___|  /\___  >__/\_ \
     \/        \/     \/     \/      \/
   https://hub.docker.com/u/binhex/

2019-05-06 13:08:47.140703 [info] System information Linux 8e5db03d43ac 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 GNU/Linux
2019-05-06 13:08:47.175570 [info] PUID defined as '999'
2019-05-06 13:08:47.204582 [info] PGID defined as '999'
2019-05-06 13:08:47.258333 [info] UMASK defined as '000'
2019-05-06 13:08:47.294058 [info] Permissions already set for volume mappings
2019-05-06 13:08:47.324459 [info] DELUGE_DAEMON_LOG_LEVEL defined as 'info'
2019-05-06 13:08:47.349228 [info] DELUGE_WEB_LOG_LEVEL defined as 'debug'
2019-05-06 13:08:47.377825 [info] VPN_ENABLED defined as 'yes'
2019-05-06 13:08:47.411000 [crit] No OpenVPN config file located in /config/openvpn/ (ovpn extension), please download from your VPN provider and then restart this container, exiting...
```

What could be the reason for this difference in startup (all the other docker containers started globally or individually are fine - it is just `delugevpn` which has this behaviour so I believe the problem is with the way I start this particular container)

**Comment by binhex** [comment] 2019-05-08 17:26
Duplicate of post on forum, resolved.

**Closed** 2019-05-08 17:26 UTC
