### ISSUE TITLE
Cant access Deluge while vpn enabled

### ISSUE THREAD

**Issue by Alacard** [binhex/arch-delugevpn#31] opened 2017-08-01 19:10 UTC
For the life of me I cant access deluge docker from lan, while vpn is enable ive tryed all combo's 
VPN=Off,privoxy=Off     can access
VPN=Off,privoxy=On     can access
VPN=On,privoxy=On     cant access
VPN=On,privoxy=Off     cant access

Ive tryed webui and also remote daemon (i can access both with VPN turned off)
hopefully im just over looking something.

[deluged.txt](https://github.com/binhex/arch-delugevpn/files/1191641/deluged.txt)
[supervisord.txt](https://github.com/binhex/arch-delugevpn/files/1191640/supervisord.txt)

**Comment by noaht8um** [comment] 2017-08-15 02:23
@Alacard I am having the same issue. I think the issue is that deluge is binding to the wrong interface. It's taking tun0 instead of eth0 for the bind interface. I tried setting this manually, but I can't get any settings to stick.

@binhex If there is a way to simply specify an interface for deluge to bind to, that should be enough to close this issue.

Thanks!

**Comment by noaht8um** [comment] 2017-08-15 02:29
@binhex I figured it out; didn't realize that the subnet I was accessing deluge from wasn't in the allowed subnets group.

@Alacard If you don't have your subnet defined in the environment variables, you cannot access Deluge; found this out the hard way lol.

**Closed** 2017-08-17 08:33 UTC
